### ISSUE TITLE
Importing lycon causes Fatal Python Error

### ISSUE THREAD

**Issue by nicholaspad** [ethereon/lycon#14]
This problem started happening just yesterday. Prior, lycon imported and functioned with zero problems.

Running`import lycon` causes:
`Fatal Python error: PyThreadState_Get: no current thread`
`Abort trap: 6`

Python 2.7.15
macOS 10.13.6 (High Sierra)

**Comment by ilarele** [comment]
On my laptop, the import causes the same error in a conda env with **Python 3.6.6**, but works fine in a conda env with *Python 2.7.15*.

OS: macOS 10.13.6 (High Sierra)

**Comment by ilarele** [comment]
A workaround: downgrade python to 3.6.1: _conda install python=3.6.1_
