### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by chihyuwang** [ethereon/lycon#5]
Following the install instructions,
(1)my first step : checking all the dependency ,
sudo apt-get install cmake build-essential libjpeg-dev libpng-dev
below is the result:

nvidia@tegra-ubuntu:~$ sudo apt-get install cmake build-essential libjpeg-dev libpng-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
build-essential is already the newest version (12.1ubuntu2).
libjpeg-dev is already the newest version (8c-2ubuntu8).
libpng12-dev is already the newest version (1.2.54-1ubuntu1).
cmake is already the newest version (3.5.1-1ubuntu3).
The following packages were automatically installed and are no longer required:
  bind9-host geoip-database libavahi-core7 libbind9-140 libdns162 libgeoip1 libisc160 libisccc140 libisccfg140 liblwres141
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.

(2)my second step : install lycon,
sudo pip install lycon
below is the result:

nvidia@tegra-ubuntu:~$ sudo pip install lycon
The directory '/home/nvidia/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nvidia/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting lycon
  Downloading lycon-0.1.9.tar.gz (129kB)
    100% |████████████████████████████████| 133kB 1.2MB/s
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from lycon)
Installing collected packages: lycon
  Running setup.py install for lycon ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nYL9iq/lycon/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x2BoCo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-2.7
    creating build/lib.linux-aarch64-2.7/lycon
    copying lycon/enum.py -> build/lib.linux-aarch64-2.7/lycon
    copying lycon/__init__.py -> build/lib.linux-aarch64-2.7/lycon
    copying lycon/core.py -> build/lib.linux-aarch64-2.7/lycon
    running egg_info
    writing requirements to lycon.egg-info/requires.txt
    writing lycon.egg-info/PKG-INFO
    writing top-level names to lycon.egg-info/top_level.txt
    writing dependency_links to lycon.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'lycon.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'lycon.egg-info/SOURCES.txt'
    running build_ext
    Source path is /tmp/pip-build-nYL9iq/lycon
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.8")
    -- Found PNG: /usr/lib/aarch64-linux-gnu/libpng.so (found version "1.2.54")
    -- Found JPEG: /usr/lib/aarch64-linux-gnu/libjpeg.so
    -- Python binary: /usr/bin/python
    -- Python include path: /usr/include/python2.7
    -- Python library path: /usr/lib
    -- Python version: 2.7
    -- Expanding search for libpython
    -- Python library path: /usr/lib/aarch64-linux-gnu/libpython2.7.so
    -- NumPy include path: /usr/local/lib/python2.7/dist-packages/numpy/core/include
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-nYL9iq/lycon/build/temp.linux-aarch64-2.7
    Starting build with 4 jobs
    Scanning dependencies of target lycon
    [  7%] Building CXX object CMakeFiles/lycon.dir/src/lycon/io/base.cc.o
    [  7%] Building CXX object CMakeFiles/lycon.dir/src/lycon/io/exif.cc.o
    [ 10%] Building CXX object CMakeFiles/lycon.dir/src/lycon/io/io.cc.o
    [ 14%] Building CXX object CMakeFiles/lycon.dir/src/lycon/io/bitstream.cc.o
    [ 17%] Building CXX object CMakeFiles/lycon.dir/src/lycon/io/jpeg.cc.o
    [ 21%] Building CXX object CMakeFiles/lycon.dir/src/lycon/io/png.cc.o
    [ 25%] Building CXX object CMakeFiles/lycon.dir/src/lycon/mat/allocator.cc.o
    [ 28%] Building CXX object CMakeFiles/lycon.dir/src/lycon/mat/convert.cc.o
    [ 32%] Building CXX object CMakeFiles/lycon.dir/src/lycon/mat/copy.cc.o
    [ 35%] Building CXX object CMakeFiles/lycon.dir/src/lycon/mat/io_array.cc.o
    [ 39%] Building CXX object CMakeFiles/lycon.dir/src/lycon/mat/iterator.cc.o
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScaleAbs_SIMD<unsigned char, unsigned char, float>::operator()(const uchar*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:289:65: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                     vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst_0)), vqmovn_u32(cv_vrndq_u32_f32(v_dst_1)));
                                                                     ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScaleAbs_SIMD<signed char, unsigned char, float>::operator()(const schar*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:331:65: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                     vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst_0)), vqmovn_u32(cv_vrndq_u32_f32(v_dst_1)));
                                                                     ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScaleAbs_SIMD<short unsigned int, unsigned char, float>::operator()(const ushort*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:362:65: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                     vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst_0)), vqmovn_u32(cv_vrndq_u32_f32(v_dst_1)));
                                                                     ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScaleAbs_SIMD<short int, unsigned char, float>::operator()(const short int*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:391:65: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                     vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst_0)), vqmovn_u32(cv_vrndq_u32_f32(v_dst_1)));
                                                                     ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScaleAbs_SIMD<int, unsigned char, float>::operator()(const int*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:411:70: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x4_t v_dsti_0 = vqmovn_u32(cv_vrndq_u32_f32(v_dst_0));
                                                                          ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScaleAbs_SIMD<float, unsigned char, float>::operator()(const float*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:436:70: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x4_t v_dsti_0 = vqmovn_u32(cv_vrndq_u32_f32(v_dst_0));
                                                                          ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<unsigned char, unsigned char, float>::operator()(const uchar*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:1981:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<unsigned char, signed char, float>::operator()(const uchar*, lycon::schar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2002:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<unsigned char, short unsigned int, float>::operator()(const uchar*, lycon::ushort*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2023:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<unsigned char, short int, float>::operator()(const uchar*, short int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2044:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<unsigned char, int, float>::operator()(const uchar*, int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2065:55: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 vst1q_s32(dst + x, cv_vrndq_s32_f32(v_dst1));
                                                           ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<signed char, unsigned char, float>::operator()(const schar*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2107:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<signed char, signed char, float>::operator()(const schar*, lycon::schar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2128:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<signed char, short unsigned int, float>::operator()(const schar*, lycon::ushort*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2149:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<signed char, short int, float>::operator()(const schar*, short int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2170:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<signed char, int, float>::operator()(const schar*, int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2191:55: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 vst1q_s32(dst + x, cv_vrndq_s32_f32(v_dst1));
                                                           ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short unsigned int, unsigned char, float>::operator()(const ushort*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2233:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short unsigned int, signed char, float>::operator()(const ushort*, lycon::schar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2254:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short unsigned int, short unsigned int, float>::operator()(const ushort*, lycon::ushort*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2275:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short unsigned int, short int, float>::operator()(const ushort*, short int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2296:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short unsigned int, int, float>::operator()(const ushort*, int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2317:55: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 vst1q_s32(dst + x, cv_vrndq_s32_f32(v_dst1));
                                                           ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short int, unsigned char, float>::operator()(const short int*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2359:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short int, signed char, float>::operator()(const short int*, lycon::schar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2380:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<short int, short unsigned int, float>::operator()(const short int*, lycon::ushort*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2401:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<int, unsigned char, float>::operator()(const int*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2442:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<int, signed char, float>::operator()(const int*, lycon::schar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2462:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<int, short unsigned int, float>::operator()(const int*, lycon::ushort*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2482:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<int, short int, float>::operator()(const int*, short int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2502:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<float, unsigned char, float>::operator()(const float*, lycon::uchar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2524:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<float, signed char, float>::operator()(const float*, lycon::schar*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2544:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<float, short unsigned int, float>::operator()(const float*, lycon::ushort*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2564:79: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint16x8_t v_dst = vcombine_u16(vqmovn_u32(cv_vrndq_u32_f32(v_dst1)), vqmovn_u32(cv_vrndq_u32_f32(v_dst2)));
                                                                                   ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<float, short int, float>::operator()(const float*, short int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2584:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_dst1)), vqmovn_s32(cv_vrndq_s32_f32(v_dst2)));
                                                                                  ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::cvtScale_SIMD<float, int, float>::operator()(const float*, int*, int, float, float) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2600:107: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 vst1q_s32(dst + x, cv_vrndq_s32_f32(vaddq_f32(vmulq_f32(vld1q_f32(src + x), v_scale), v_shift)));
                                                                                                               ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In function ‘void lycon::cvtScale_(const T*, size_t, DT*, size_t, lycon::Size, WT, WT) [with T = short int; DT = short int; WT = float; size_t = long unsigned int; lycon::Size = lycon::Size_<int>]’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2696:70: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                           vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_tmp1)), vqmovn_s32(cv_vrndq_s32_f32(v_tmp2))));
                                                                          ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In function ‘void lycon::cvtScale_(const T*, size_t, DT*, size_t, lycon::Size, WT, WT) [with T = short int; DT = int; WT = float; size_t = long unsigned int; lycon::Size = lycon::Size_<int>]’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:2765:55: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 vst1q_s32(dst + x, cv_vrndq_s32_f32(v_tmp1));
                                                           ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::Cvt_SIMD<float, unsigned char>::operator()(const float*, lycon::uchar*, int) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:3378:68: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint32x4_t v_src1 = cv_vrndq_u32_f32(vld1q_f32(src + x));
                                                                        ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::Cvt_SIMD<float, signed char>::operator()(const float*, lycon::schar*, int) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:3399:67: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int32x4_t v_src1 = cv_vrndq_s32_f32(vld1q_f32(src + x));
                                                                       ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::Cvt_SIMD<float, short unsigned int>::operator()(const float*, lycon::ushort*, int) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:3420:68: error: ‘cv_vrndq_u32_f32’ was not declared in this scope
                 uint32x4_t v_src1 = cv_vrndq_u32_f32(vld1q_f32(src + x));
                                                                        ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In member function ‘int lycon::Cvt_SIMD<float, int>::operator()(const float*, int*, int) const’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:3436:67: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 vst1q_s32(dst + x, cv_vrndq_s32_f32(vld1q_f32(src + x)));
                                                                       ^
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc: In function ‘void lycon::cvt_(const T*, size_t, DT*, size_t, lycon::Size) [with T = float; DT = short int; size_t = long unsigned int; lycon::Size = lycon::Size_<int>]’:
    /tmp/pip-build-nYL9iq/lycon/src/lycon/mat/convert.cc:3739:78: error: ‘cv_vrndq_s32_f32’ was not declared in this scope
                 int16x8_t v_dst = vcombine_s16(vqmovn_s32(cv_vrndq_s32_f32(v_src1)), vqmovn_s32(cv_vrndq_s32_f32(v_src2)));
                                                                                  ^
    CMakeFiles/lycon.dir/build.make:230: recipe for target 'CMakeFiles/lycon.dir/src/lycon/mat/convert.cc.o' failed
    make[2]: *** [CMakeFiles/lycon.dir/src/lycon/mat/convert.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/lycon.dir/all' failed
    make[1]: *** [CMakeFiles/lycon.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
        * Failed to build the Lycon native extension.
        * [Error] Failed to exceute: /usr/bin/make -j 4

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nYL9iq/lycon/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x2BoCo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 255 in /tmp/pip-build-nYL9iq/lycon/
nvidia@tegra-ubuntu:~$

How to fix the errors?

**Comment by ethereon** [comment]
Looks like it's missing the header for ARM NEON intrinsics. Adding `#include <arm_neon.h>` (if I recall correctly) should fix it.

However, note that lycon is untested on `aarch64` and there may be further issues.

**Comment by chihyuwang** [comment]
thanks for your help.

**Comment by nikitabalabin** [comment]
`sudo apt-get install cmake build-essential libjpeg-dev libpng-dev`

**Comment by stevendbrown** [comment]
Converting all the offending calls from `cv_vrndq_u32_f32` and `cv_vrndq_s32_f32` to `vcvtnq_u32_f32` and `vcvtnq_s32_f32`, respectively, also works and the resulting code compiles and runs on Intel CPUs (in my hands) as well as Apple Silicon. This method does not introduce a dependency on OpenCV as in PR #18 .
